# Generated by Django 3.2.5 on 2021-07-26 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pageversion_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='versions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pageversion', verbose_name='Версії'),
        ),
    ]
